<?php

namespace App\Database;

class DBColumns
{
    public static $tabla_referencias = [
        "lote_id",
        "Codigo",
        "Referencia",
        "Origen",
        "Destino",
        "Cliente Destino",
        "Fecha de Cargue",
        "Empresa",
        "Aliado",
        "Empresa TRT",
        "Placa",
        "Monitoreo Finalizado",
        "Finalizado Por",
        "Status Actual",
        "Fecha / Hora status actual",
        "Status tiempo",
        "Fecha / Hora aprox. llegada(ETA)",
        "Fecha / Hora Compromiso llegada",
        "Fecha / Hora Ingreso Vigilancia",
        "Fecha / Hora Salida Vigilancia",
        "Carreta",
        "Procesamiento OPL",
        "Nombre coordinador",
        "Presenta para Carga - Fecha",
        "Presenta para Carga - Monitorista",
        "Presenta para Carga - Observación",
        "Llegada a Origen - Fecha",
        "Llegada a Origen - Monitorista",
        "Llegada a Origen - Observación",
        "Pre - Enturnamiento - Fecha",
        "Pre - Enturnamiento - Monitorista",
        "Pre - Enturnamiento - Observación",
        "Enturnamiento - Fecha",
        "Enturnamiento - Monitorista",
        "Enturnamiento - Observación",
        "Inicio de Carga - Fecha",
        "Inicio de Carga - Monitorista",
        "Inicio de Carga - Observación",
        "Fin de carga - Fecha",
        "Fin de carga - Monitorista",
        "Fin de carga - Observación",
        "Inicio de Toldeo - Fecha",
        "Inicio de Toldeo - Monitorista",
        "Inicio de Toldeo - Observación",
        "Fin de Toldeo - Fecha",
        "Fin de Toldeo - Monitorista",
        "Fin de Toldeo - Observación",
        "Generación de Documento - Fecha",
        "Generación de Documento - Monitorista",
        "Generación de Documento - Observación",
        "Entrega de Documento - Fecha",
        "Entrega de Documento - Monitorista",
        "Entrega de Documento - Observación",
        "Inicio Ruta - Fecha",
        "Inicio Ruta - Monitorista",
        "Inicio Ruta - Observación",
        "En ruta - Fecha",
        "En ruta - Monitorista",
        "En ruta - Observación",
        "Llegada a Destino - Fecha",
        "Llegada a Destino - Monitorista",
        "Llegada a Destino - Observación",
        "Inicio Descargue - Fecha",
        "Inicio Descargue - Monitorista",
        "Inicio Descargue - Observación",
        "Fin Descargue - Fecha",
        "Fin Descargue - Monitorista",
        "Fin Descargue - Observación",
        "En Resguardo - Fecha",
        "En Resguardo - Monitorista",
        "En Resguardo - Observación",
        "¡ALERTA DE RETRASO DE DESCARGA! - Fecha",
        "¡ALERTA DE RETRASO DE DESCARGA! - Monitorista",
        "¡ALERTA DE RETRASO DE DESCARGA! - Observación",
        "Parada por Otros - Fecha",
        "Parada por Otros - Monitorista",
        "Parada por Otros - Observación",
        "PARADA POR DESCANSO - Fecha",
        "PARADA POR DESCANSO - Monitorista",
        "PARADA POR DESCANSO - Observación",
        "Operador no responde - Fecha",
        "Operador no responde - Monitorista",
        "Operador no responde - Observación"
    ];
}
