<?php

namespace App\Database;

class DBColumns
{
    public static $campos_referencias_excel =  [
        "LOTE_ID",
        "CODIGO",
        "REFERENCIA",
        "ORIGEN",
        "DESTINO",
        "CLIENTE DESTINO",
        "FECHA DE CARGUE",
        "EMPRESA",
        "ALIADO",
        "EMPRESA TRT",
        "PLACA",
        "MONITOREO FINALIZADO",
        "FINALIZADO POR",
        "STATUS ACTUAL",
        "FECHA / HORA STATUS ACTUAL",
        "STATUS TIEMPO",
        "FECHA / HORA APROX. LLEGADA(ETA)",
        "FECHA / HORA COMPROMISO LLEGADA",
        "FECHA / HORA INGRESO VIGILANCIA",
        "FECHA / HORA SALIDA VIGILANCIA",
        "CARRETA",
        "PROCESAMIENTO OPL",
        "NOMBRE COORDINADOR",
        "PRESENTA PARA CARGA - FECHA",
        "PRESENTA PARA CARGA - MONITORISTA",
        "PRESENTA PARA CARGA - OBSERVACION",
        "LLEGADA A ORIGEN - FECHA",
        "LLEGADA A ORIGEN - MONITORISTA",
        "LLEGADA A ORIGEN - OBSERVACION",
        "PRE - ENTURNAMIENTO - FECHA",
        "PRE - ENTURNAMIENTO - MONITORISTA",
        "PRE - ENTURNAMIENTO - OBSERVACION",
        "ENTURNAMIENTO - FECHA",
        "ENTURNAMIENTO - MONITORISTA",
        "ENTURNAMIENTO - OBSERVACION",
        "INICIO DE CARGA - FECHA",
        "INICIO DE CARGA - MONITORISTA",
        "INICIO DE CARGA - OBSERVACION",
        "FIN DE CARGA - FECHA",
        "FIN DE CARGA - MONITORISTA",
        "FIN DE CARGA - OBSERVACION",
        "INICIO DE TOLDEO - FECHA",
        "INICIO DE TOLDEO - MONITORISTA",
        "INICIO DE TOLDEO - OBSERVACION",
        "FIN DE TOLDEO - FECHA",
        "FIN DE TOLDEO - MONITORISTA",
        "FIN DE TOLDEO - OBSERVACION",
        "GENERACION DE DOCUMENTO - FECHA",
        "GENERACION DE DOCUMENTO - MONITORISTA",
        "GENERACION DE DOCUMENTO - OBSERVACION",
        "ENTREGA DE DOCUMENTO - FECHA",
        "ENTREGA DE DOCUMENTO - MONITORISTA",
        "ENTREGA DE DOCUMENTO - OBSERVACION",
        "INICIO RUTA - FECHA",
        "INICIO RUTA - MONITORISTA",
        "INICIO RUTA - OBSERVACION",
        "EN RUTA - FECHA",
        "EN RUTA - MONITORISTA",
        "EN RUTA - OBSERVACION",
        "LLEGADA A DESTINO - FECHA",
        "LLEGADA A DESTINO - MONITORISTA",
        "LLEGADA A DESTINO - OBSERVACION",
        "INICIO DESCARGUE - FECHA",
        "INICIO DESCARGUE - MONITORISTA",
        "INICIO DESCARGUE - OBSERVACION",
        "FIN DESCARGUE - FECHA",
        "FIN DESCARGUE - MONITORISTA",
        "FIN DESCARGUE - OBSERVACION",
        "EN RESGUARDO - FECHA",
        "EN RESGUARDO - MONITORISTA",
        "EN RESGUARDO - OBSERVACION",
        "ALERTA DE RETRASO DE DESCARGA - FECHA",
        "ALERTA DE RETRASO DE DESCARGA - MONITORISTA",
        "ALERTA DE RETRASO DE DESCARGA - OBSERVACION",
        "PARADA POR OTROS - FECHA",
        "PARADA POR OTROS - MONITORISTA",
        "PARADA POR OTROS - OBSERVACION",
        "PARADA POR DESCANSO - FECHA",
        "PARADA POR DESCANSO - MONITORISTA",
        "PARADA POR DESCANSO - OBSERVACION",
        "OPERADOR NO RESPONDE - FECHA",
        "OPERADOR NO RESPONDE - MONITORISTA",
        "OPERADOR NO RESPONDE - OBSERVACION"
    ];

    public static $table_referencias=[
        "lote_id",
        "codigo",
        "ref",
        "origen",
        "destino",
        "cliente_destino",
        "fecha_de_cargue",
        "empresa",
        "aliado",
        "empresa_trt",
        "placa",
        "monitoreo_finalizado",
        "finalizado_por",
        "status_actual",
        "fecha_hora_status_actual",
        "status_tiempo",
        "fecha_hora_aprox_llegada_eta",
        "fecha_hora_compromiso_llegada",
        "fecha_hora_ingreso_vigilancia",
        "fecha_hora_salida_vigilancia",
        "carreta",
        "procesamiento_opl",
        "nombre_coordinador",
        "presenta_para_carga_fecha",
        "presenta_para_carga_monitorista",
        "presenta_para_carga_observacion",
        "llegada_a_origen_fecha",
        "llegada_a_origen_monitorista",
        "llegada_a_origen_observacion",
        "pre_enturnamiento_fecha",
        "pre_enturnamiento_monitorista",
        "pre_enturnamiento_observacion",
        "enturnamiento_fecha",
        "enturnamiento_monitorista",
        "enturnamiento_observacion",
        "inicio_de_carga_fecha",
        "inicio_de_carga_monitorista",
        "inicio_de_carga_observacion",
        "fin_de_carga_fecha",
        "fin_de_carga_monitorista",
        "fin_de_carga_observacion",
        "inicio_de_toldeo_fecha",
        "inicio_de_toldeo_monitorista",
        "inicio_de_toldeo_observacion",
        "fin_de_toldeo_fecha",
        "fin_de_toldeo_monitorista",
        "fin_de_toldeo_observacion",
        "generacion_de_documento_fecha",
        "generacion_de_documento_monitorista",
        "generacion_de_documento_observacion",
        "entrega_de_documento_fecha",
        "entrega_de_documento_monitorista",
        "entrega_de_documento_observacion",
        "inicio_ruta_fecha",
        "inicio_ruta_monitorista",
        "inicio_ruta_observacion",
        "en_ruta_fecha",
        "en_ruta_monitorista",
        "en_ruta_observacion",
        "llegada_a_destino_fecha",
        "llegada_a_destino_monitorista",
        "llegada_a_destino_observacion",
        "inicio_descargue_fecha",
        "inicio_descargue_monitorista",
        "inicio_descargue_observacion",
        "fin_descargue_fecha",
        "fin_descargue_monitorista",
        "fin_descargue_observacion",
        "en_resguardo_fecha",
        "en_resguardo_monitorista",
        "en_resguardo_observacion",
        "alerta_de_retraso_de_descarga_fecha",
        "alerta_de_retraso_de_descarga_monitorista",
        "alerta_de_retraso_de_descarga_observacion",
        "parada_por_otros_fecha",
        "parada_por_otros_monitorista",
        "parada_por_otros_observacion",
        "parada_por_descanso_fecha",
        "parada_por_descanso_monitorista",
        "parada_por_descanso_observacion",
        "operador_no_responde_fecha",
        "operador_no_responde_monitorista",
        "operador_no_responde_observacion"
    ];
}
